# Generated by Django 4.0 on 2021-12-19 16:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0002_account_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 12, 19, 17, 42, 45, 677234)),
        ),
    ]
