# Generated by Django 4.0 on 2021-12-19 19:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0003_entry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='contract',
            field=models.CharField(choices=[('T', 'tenant'), ('S', 'sublet'), ('U', 'unknown')], default='unspecified', max_length=1),
        ),
        migrations.AlterField(
            model_name='entry',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 12, 19, 20, 22, 23, 123932)),
        ),
        migrations.AlterField(
            model_name='entry',
            name='type',
            field=models.CharField(choices=[('INC', 'income'), ('EXP', 'expense')], max_length=3),
        ),
    ]
