# Generated by Django 4.0 on 2021-12-19 21:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0005_alter_account_contract_alter_entry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distribution',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribution', related_query_name='distributions', to='bookkeeping.account'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 12, 19, 22, 6, 14, 540457)),
        ),
    ]
