# Generated by Django 4.0 on 2021-12-19 21:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0007_alter_distribution_account_alter_distribution_entry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distribution',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookkeeping.entry'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 12, 19, 22, 20, 51, 360266)),
        ),
    ]
