# Generated by Django 4.0 on 2021-12-29 10:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0009_account_email_account_rent_account_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='contract',
            field=models.CharField(choices=[('tenant', 'Tenant'), ('sublet', 'Sublet'), ('legal', 'Legal'), ('unspecified', 'Unspecified')], default='unspecified', max_length=12),
        ),
        migrations.AlterField(
            model_name='account',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2021, 12, 29, 11, 46, 21, 740309)),
        ),
        migrations.AlterField(
            model_name='entry',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 12, 29, 11, 46, 21, 765450)),
        ),
    ]
