# Generated by Django 4.0 on 2022-01-08 13:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0010_alter_account_contract_alter_account_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2022, 1, 8, 14, 20, 28, 174846)),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='bookkeeping.entry'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 1, 8, 14, 20, 28, 214764)),
        ),
    ]
