# Generated by Django 4.0 on 2022-01-26 17:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0014_account_is_active_alter_account_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='gender',
            field=models.CharField(choices=[('M', 'male'), ('F', 'female')], default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='entry',
            name='VAT_rate',
            field=models.CharField(choices=[('NOR', 'normal(20%)'), ('MID', 'middle(10%)'), ('RED', 'reduced(5,5%)'), ('SPE', 'special(2,1%)'), ('ND', 'undetermined')], default='ND', max_length=3),
        ),
        migrations.AlterField(
            model_name='account',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2022, 1, 26, 18, 15, 40, 716242)),
        ),
        migrations.AlterField(
            model_name='entry',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 1, 26, 18, 15, 40, 758646)),
        ),
    ]
