# Generated by Django 4.0 on 2022-01-30 12:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0015_account_gender_entry_vat_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2022, 1, 30, 13, 45, 46, 793509)),
        ),
        migrations.AlterField(
            model_name='entry',
            name='VAT_rate',
            field=models.CharField(choices=[('NOR', 'normal(20%)'), ('MID', 'middle(10%)'), ('RED', 'reduced(5,5%)'), ('SPE', 'special(2,1%)'), ('NUL', 'null'), ('ND', 'undetermined')], default='ND', max_length=3),
        ),
        migrations.AlterField(
            model_name='entry',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 1, 30, 13, 45, 46, 831921)),
        ),
    ]
