# Generated by Django 4.0 on 2022-01-30 21:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0021_alter_account_start_date_alter_entry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2022, 1, 30, 22, 2, 21, 990087)),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='entry',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 1, 30, 22, 2, 22, 19562)),
        ),
    ]
