# Generated by Django 4.0 on 2022-02-01 10:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0022_alter_account_start_date_alter_distribution_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='rent',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='account',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2022, 2, 1, 11, 29, 0, 648945)),
        ),
        migrations.AlterField(
            model_name='entry',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 2, 1, 11, 29, 0, 675956)),
        ),
    ]
